services:
  web:
    build: .
    platform: linux/amd64
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "31022:3000"
    networks:
      - planning
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb:27017
  mongodb:
    image: mongo:7.0
    restart: always
    volumes:
      - '.mongo-planning:/data/db'
    networks:
      - planning

networks:
  planning:
    driver: bridge
